### ISSUE TITLE
Retransmit frame to get acknowlegment

### ISSUE THREAD

**Issue by mstfbirinci** [gisce/iec870ree#7]
link_state_request, remote_link_reposition, authentication or read_integerated_total methods send frames, but sometimes we can not get any response and connection is stalled. 

I think, if we can not get any response for any frame, we should retransmit the frame until getting acknowledment or should try max 5 times.

Did you faced with this problem? What do you think about this?

**Comment by ecarreras** [comment]
We didn't found this problem, but your proposal it's a good improvement. We will think about it with @MiquelIR

**Comment by MiquelIR** [comment]
Hi @mstfbirinci ! Are you getting this stalling using the current version of the code?

It's true that it fell onto some stalled state before but I think we fixed that with the disconnection process.

If you are still getting it we can look into it to find some viable solutions.

**Comment by mstfbirinci** [comment]
Hi @ecarreras @MiquelIR 

For example, it send link_state_request frame and didn't get any response. After the 60 sec(queue timeout) it raised queue.empty exception.

I think, it caused by gsm signal loss.

**Comment by MiquelIR** [comment]
@mstfbirinci Hi! I don't know if you are still using or checking this project but I coded a modification to allow those retries you asked for.

It's pretty simple but it resends the 2 handshake messages.

**Comment by ecarreras** [comment]
Fixed #10
